agravos = {
    'A90': 'A90 - DENGUE',
    'A630': 'A630 - CONDILOMA ACUMINADO (VERRUGAS ANOGENITAIS)',
    'A60':'A60 - HERPES GENITAL',
    'A53': 'A53 - SIFILIS EM ADULTO',
    'A539': 'A539 - SIFILIS NAO ESPECIFICADA',
    'A010': 'A010 - FEBRE TIFOIDE',
    'A379': 'A379 - COQUELUCHE',
    'A959': 'A959 - FEBRE AMARELA',
    'A509': 'A509 - SIFILIS CONGENITA',
    'A309': 'A309 - HANSNENIASE',
    'A279': 'A279 - LEPTOSPIROSE',
    'A35': 'A35 - TETANO ACIDENTAL',
    'A369': 'A369 - DIFTERIA',
    'A809': 'A809 - PARALISIA FLACIDA AGUDA POLIOMIELITE',
    'A988': 'A988 - HANTAVIROSE',
    'A169': 'A169 - TUBERCULOSE',
    'A080': 'A080 - ROTAVIRUS',
    'A009': 'A009 - COLERA',
    'A928': 'A928 - DOENCA AGUDA PELO VIRUS ZIKA',
    'A33': 'A33 - TETANO NEONATAL',
    'A779': 'A779 - FEBRE MACULOSA - RICKETTSIOSES',
    'A719': 'A719 - TRACOMA',
    'A920': 'A920 - FEBRE DE CHIKUNGUNYA',
    'A051': 'A051 - BOTULISMO',
    'A810': 'A810 - DOENCA DE CREUTZFELDT-JACOB',
    'A692': 'A692 - DOENCA DE LYME',
    'A938': 'A938 - OUTRAS FEBRES VIRAIS ESPECIFICADAS TRANSMITIDAS POR ARTROPODES',
    'A23': 'A23 - BRUCELOSE',
    'A923': 'A923 - FEBRE DO NILO',
    'A829': 'A829 - RAIVA HUMANA',
    'A219': 'A219 - TULAREMIA',
    'A969': 'A969 - FEBRE HEMORRAGICA POR ARENAVIRUS',
    'A08': 'A08 - SINDROME DIARREICA AGUDA',
    'A209': 'A209 - PESTE',
    'A229': 'A229 - CARBUNCULO OU ANTRAZ',
    'B551': 'LEISHMANIOSE TEGUMENTAR AMERICANA',
    'B550': 'LEISHMANIOSE VISCERAL',
    'B24': 'Doença pelo vírus da imunodeficiência humana [HIV]',
    'B19': 'HEPATITES VIRAIS',
    'B09': 'DOENCAS EXANTEMATICAS',
    'B659': 'ESQUISTOSSOMOSE',
    'B571': 'DOENCA DE CHAGAS AGUDA',
    'B019': 'VARICELA',
    'B26': 'Caxumba',
    'B54': 'MALARIA',
    'B58': 'Toxoplasmose',
    'B01': 'Varicela',
    'B749': 'FILARIOSE NAO ESPECIFICADA',
    'B03': 'VARIOLA',
    'D593': 'Sindrome hemolitico-uremica',
    'D699': 'SINDROME DA FEBRE HEMORRAGICA AGUDA',
    'F99': 'Transtorno mental não especificado',
    'G039': 'MENINGITE',
    'G043': 'SINDROME NEUROLOGICA AGUDA',
    'H833': 'Doenças do ouvido interno',
    'J06': 'SINDROME GRIPAL',
    'J07': 'SINDROME RESPIRATORIA AGUDA',
    'J189': 'Influenza e pneumonia',
    'J11': 'INFLUENZA HUMANA POR NOVO SUBTIPO (PANDEMICO)',
    'J64': 'PNEUMONIA',
    'L989': 'Afeccoes da pele e do tecido subcutaneo',
    'N72': 'Doenca inflamatoria do colo do utero',
    'N485': 'Doenças dos órgãos genitais masculinos',
    'N199': 'SINDROME DA INSUFICIENCIA RENAL AGUDA',
    'O981': 'Complicacoes da gravidez',
    'O986': 'Doencas causadas por protozoarios complicando a gravidez, o parto e o puerperio',
    'P350': 'Sindrome da rubeola congenita',
    'P371': 'Toxoplasmose congenita',
    'R17': 'SINDROME ICTERICA AGUDA',
    'R36': 'Secrecao uretral',
    'R699': 'OUTRAS SINDROMES',
    'T659': 'INTOXICACAO EXOGENA',
    'Y59': 'EVENTOS ADVERSOS POS-VACINACAO',
    'Y09': 'AGRESSAO',
    'Y96': 'Circunstancia relativa as condicoes de trabalho',
    'X29': 'Contato com animais e plantas venenosos',
    'W64': 'Exposição a forças mecânicas animadas',
    'Z209': 'Contato com exposicao a doencas transmissiveis nao especificadas',
    'Z206': 'Contato com e exposicao ao virus da imunodeficiencia humana [HIV]',
    'Z21': 'Estado de infeccao assintomatica pelo virus da imunodeficiencia humana [HIV]',
    'Z579': 'Exposicao ocupacional a fatores de risco',
}